spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user
      username: root
      password: rootpassword
      uri: mongodb://root:rootpassword@localhost:27017/user
