---
version: "3.4"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - retail-banking-cqrs-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - retail-banking-cqrs-network

  mongo-container:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - retail-banking-cqrs-network

  mysql-container:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    volumes:
      - mysql-data-container:/var/lib/mysql
      - ./mysql-data-container/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - retail-banking-cqrs-network

  axon-container:
    image: axoniq/axonserver:latest
    restart: always
    ports:
    - '8024:8024'
    - '8124:8124'
    networks:
      - retail-banking-cqrs-network

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql-data-container:
    driver: local
  mongodb_data_container:

networks:
  retail-banking-cqrs-network: